const ballTypes = [
  { value: "供球" },
  { value: "YONEX" },
  { value: "YONEX AS-50" },
  { value: "YONEX AS-30" },
  { value: "YONEX AS-20" },
  { value: "YONEX ACB-TR" },
  { value: "YONEX ACB-33" },
  { value: "VICTOR" },
  { value: "VICTOR B-MA" },
  { value: "VICTOR B-MA-1" },
  { value: "VICTOR B-01N" },
  { value: "VICTOR B-01" },
  { value: "VICTOR B-03" },
  { value: "VICTOR B-09" },
  { value: "VICTOR B-04" },
  { value: "VICTOR B-15" },
  { value: "VICTOR B-08" },
  { value: "VICTOR B-12" },
  { value: "RSL" },
  { value: "RSL No.1" },
  { value: "RSL No.2" },
  { value: "RSL No.3" },
  { value: "RSL No.4" },
  { value: "RSL No.5" },
  { value: "RSL No.10" },
  { value: "MMOA" },
  { value: "MMOA MS-101" },
  { value: "MMOA MS-99" },
  { value: "MMOA MS-95" },
  { value: "MMOA MS-90" },
  { value: "MMOA MS-85" },
  { value: "MMOA MS-77" },
  { value: "MMOA MS-75" },
  { value: "MMOA MS-86" },
  { value: "MMOA MS-65" },
  { value: "MMOA MS-55" },
  { value: "MMOA MS-45" },
  { value: "MMOA MS-15" },
  { value: "LI-NING" },
  { value: "LI-NING C90" },
  { value: "LI-NING C80" },
  { value: "LI-NING CT-SUPER" },
  { value: "LI-NING CHAMP" },
  { value: "LI-NING G900" },
  { value: "LI-NING G800" },
  { value: "LI-NING G700" },
  { value: "LI-NING G600" },
  { value: "LI-NING G500" },
  { value: "LI-NING G300" },
  { value: "LI-NING G200" },
  { value: "JNICE" },
  { value: "JNICE AJ-50" },
  { value: "JNICE AJ-40" },
  { value: "JNICE AJ-30" },
  { value: "JNICE AJ-20" },
  { value: "JNICE AJ-10" },
  { value: "JNICE AJ-01" },
  { value: "JNICE PROAERO3" },
  { value: "EXTHREE" },
  { value: "EXTHREE X-750" },
  { value: "EXTHREE X-700" },
  { value: "EXTHREE X-600" },
  { value: "EXTHREE X-280" },
  { value: "EXTHREE X-250" },
  { value: "EXTHREE X-200" },
  { value: "Decathlon" },
  { value: "Decathlon FSC 990" },
  { value: "Decathlon FSC 930" },
  { value: "Decathlon FSC 590" },
  { value: "Decathlon FSC 560" },
  { value: "Decathlon FSC 530" },
  { value: "Decathlon FSC 100" },
  { value: "Kawasaki" },
  { value: "Wilson" }
];

export const queryBallTypesSearch = (
  queryString: string,
  cb: (result: typeof ballTypes) => void
) => {
  const regex = new RegExp(queryString, "i");
  const ballTypeList = queryString
    ? ballTypes.filter((item) => regex.test(item.value))
    : ballTypes;
  cb(ballTypeList);
};
